version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/Return.Web"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10https://github.com/Sebazzz/Return/blob/master/.github/dependabot.yml
  target-branch: develop
- package-ecosystem: npm
  directory: "/src/Return.Web"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
